# Generated by Django 4.2.5 on 2023-09-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_orderdetail_price_alter_orderdetail_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity of each product in the cart.'),
        ),
    ]
