# Generated by Django 4.2.5 on 2023-09-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_order_date'),
        ('home', '0006_alter_product_category'),
    ]

    operations = [
    ]
