# Generated by Django 4.2.5 on 2023-09-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20230918_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Ongoing'), (2, 'Cancelled'), (3, 'Rejected'), (4, 'Completed')], default=0, help_text='Status of the order.'),
        ),
    ]
