# Generated by Django 4.2.5 on 2023-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='total cost of order.', max_digits=12),
        ),
    ]
