# Generated by Django 4.2.5 on 2023-09-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_order_order_date'),
        ('home', '0009_order_order_cost'),
    ]

    operations = [
    ]
