# Generated by Django 4.2.5 on 2023-10-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20231003_0102'),
        ('home', '0011_promotion'),
    ]

    operations = [
    ]
